

debug: true
trace: false

spring:
  datasource:
    url: jdbc:mysql://localhost/company?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: mysql
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    show-sql: true
  thymeleaf.cache: false
  main.lazy-initialization: false
